### ISSUE TITLE
increase db timeout for non-tests

### ISSUE THREAD

**Issue by elnosh** [MutinyWallet/harbor#73]
I see in other issues that db timeout was increased for some tests failing. I was getting same error when running the app: 

`"ERROR harbor::core                                > error using password: timed out waiting for connection"`

I increased the timeout for non-tests as well and app started working.

**Comment by TonyGiorgio** [comment]
I think we did increase it to 30s now for non-tests. Perhaps pull down the latest master branch and check again?
