### ISSUE TITLE
GUI icons not appearing in built binary

### ISSUE THREAD

**Issue by FiliTol** [MutinyWallet/harbor#76]
**OS**: Debian 12
**Build**: rust

### Expected behaviour

Running the app from the built binary in `dist/harbor` looks exactly like running the `cargo run --features vendored`.

### Actual behaviour

Running the app from the built binary in `dist/harbor` makes the app running smoothly but icons are not appearing.

**Comment by TonyGiorgio** [comment]
It is expected that the release version runs more smoothly. But do you have an example of what you mean by the icons not showing up? A screenshot?

**Comment by FiliTol** [comment]
Window size is a bit different but I hope it makes clear the point. I may be doing something wrong in the binary building of the harbor binary btw.

![image](https://github.com/MutinyWallet/harbor/assets/106256733/2a37bb83-cd7f-45aa-b014-224289fa56dc)
![image](https://github.com/MutinyWallet/harbor/assets/106256733/e14b3755-4734-48b7-8f28-cb63e25c6bf7)

**Comment by TonyGiorgio** [comment]
Great, thank you! We'll fix.
